=== LucasGuliano/COT/COT_Data/PRG/XRTPRG.dtd
<!ELEMENT PROG (modified*, name, COT_info*, COT_slot*, COT_reserved*, MAIN_RPT, MAIN, SUBR, SUBR, SUBR, SUBR)>

<!ELEMENT MAIN_RPT (#PCDATA)>
<!ELEMENT MAIN (MAIN_ENTRY, (MAIN_ENTRY, (MAIN_ENTRY, (MAIN_ENTRY, (MAIN_ENTRY, (MAIN_ENTRY, (MAIN_ENTRY, (MAIN_ENTRY)?)?)?)?)?)?)?)?>
<!ELEMENT MAIN_ENTRY (Call, COT_SUBR*, Repeat, Interval)>
<!ATTLIST MAIN_ENTRY
	POS (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8) #REQUIRED
>
<!ELEMENT SUBR (COT_SUBR*, SUBR_ENTRY, (SUBR_ENTRY, (SUBR_ENTRY, (SUBR_ENTRY, (SUBR_ENTRY, (SUBR_ENTRY, (SUBR_ENTRY, (SUBR_ENTRY)?)?)?)?)?)?)?)?>
<!ATTLIST SUBR
	NO (1 | 2 | 3 | 4) #REQUIRED
>
<!ELEMENT SUBR_ENTRY (Call,COT_SEQ*, Repeat, Interval)>
<!ATTLIST SUBR_ENTRY
	POS (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8) #REQUIRED
>
<!ELEMENT Call (#PCDATA)>
<!ELEMENT COT_SUBR (#PCDATA)>
<!ELEMENT COT_SEQ (#PCDATA)>
<!ELEMENT Repeat (#PCDATA)>
<!ELEMENT Interval (#PCDATA)>

<!ELEMENT modified (#PCDATA)>
<!ATTLIST modified
	author CDATA #IMPLIED
	dateTime CDATA #IMPLIED
>

<!ELEMENT name (#PCDATA)>

<!ELEMENT COT_reserved (#PCDATA)>

<!ELEMENT COT_info (#PCDATA)>
<!ATTLIST COT_info
    deleted CDATA #IMPLIED
    lastUsed CDATA #IMPLIED
    version CDATA #IMPLIED
    locked CDATA #IMPLIED
>
<!ELEMENT COT_slot (#PCDATA)>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-1867.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="TESTA, Paola" dateTime="2011-03-09T19:53:32Z" />
  <name>AR Standard-A(Filter-Ratio) with PFB (384x384), thin-Be and Al/Poly context, 512x512 at 1064 1048, 120s cad</name>
  <COT_info deleted="FALSE" lastUsed="2011-03-12T02:34:09Z" version="1867" locked="FALSE"
    tag="A7465B7E71BF/1867" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>0</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-A</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="2">
      <Call>2</Call>
      <COT_SUBR>Subr-B</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>17</Call>
      <COT_SEQ>73B3707353D2/2A9B</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="2">
      <Call>97</Call>
      <COT_SEQ>CC5A5EFD5C22/2B21</COT_SEQ>
      <Repeat>4</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>30</Call>
      <COT_SEQ>CE950930BB6C/2B19</COT_SEQ>
      <Repeat>15</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/Trash/XRTPRG-140E.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 0.9x14 (1312) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="SHIN, Junho" dateTime="2007-09-18T23:46:52Z" />
  <name>Program 4</name>
  <COT_info deleted="FALSE" lastUsed="2007-09-18T23:46:52Z" version="140E" locked="FALSE"
    tag="A6952AC1AD03/140E" COTversion="0.9x14" COTbuild="1312" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>1</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-1</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>1</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="2">
      <Call>2</Call>
      <COT_SUBR>Subr-2</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>1</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-1</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>10034</Call>
      <COT_SEQ>00002DCFF5AE/23DD</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-2</COT_SUBR>
  </SUBR>
  <SUBR NO="3">
  </SUBR>
  <SUBR NO="4">
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-1BCA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="JIBBEN, Patricia" dateTime="2017-09-19T01:25:54Z" />
  <name>CCD Monitor During Bakeout - G-Band 1ms - 1kx1k - Q90 - 4th Quadrant - Al/mesh (2048ms), Al/Poly (4096ms) - w leak image-1 ms</name>
  <COT_info deleted="FALSE" lastUsed="2022-10-18T02:17:10Z" version="1BCA" locked="FALSE"
    tag="5FD86F0D15A1/1BCA" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>1</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-A</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="2">
      <Call>2</Call>
      <COT_SUBR>Subr-B</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="3">
      <Call>3</Call>
      <COT_SUBR>Subr-C</COT_SUBR>
      <Repeat>2</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>14</Call>
      <COT_SEQ>488008631C70/2E38</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>88</Call>
      <COT_SEQ>9A4F1645B2D8/2E58</COT_SEQ>
      <Repeat>2</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>34</Call>
      <COT_SEQ>02512FED6ABF/2E34</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-14AC.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="SHIMOJO, Masumi" dateTime="2008-02-28T03:34:42Z" />
  <name>CH - Al/Poly - Ti/Poly - 5 filters - Gband-FOV 512x512-low cadnse</name>
  <COT_info deleted="FALSE" lastUsed="2008-01-18T06:35:47Z" version="14AC" locked="FALSE"
    tag="1EE11E694020/14AC" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>0</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>2</Call>
      <COT_SUBR>Subr-B</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="2">
      <Call>3</Call>
      <COT_SUBR>Subr-C</COT_SUBR>
      <Repeat>24</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="3">
      <Call>1</Call>
      <COT_SUBR>Subr-A</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>100</Call>
      <COT_SEQ>000057006C90/240D</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>49</Call>
      <COT_SEQ>D7281C11F080/2665</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>42</Call>
      <COT_SEQ>50401999F735/2660</COT_SEQ>
      <Repeat>2</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="2">
      <Call>50</Call>
      <COT_SEQ>DF5013805899/2661</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>360</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/Trash/XRTPRG-1672.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 1.0x14 (1571) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="KORRECK, Kelly" dateTime="2009-03-28T02:13:09Z" />
  <name>AR-watch-Thin-be 10 min cadence</name>
  <COT_info deleted="FALSE" lastUsed="2009-03-28T02:05:30Z" version="1672" locked="FALSE"
    tag="3F1868E0EEC1/1672" COTversion="1.0x14" COTbuild="1571" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>0</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-1</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-1</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>16</Call>
      <COT_SEQ>0E462CFCED8B/28BD</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  </SUBR>
  <SUBR NO="3">
  </SUBR>
  <SUBR NO="4">
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-1577.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="MINOSHIMA, Takashi" dateTime="2008-07-02T09:24:34Z" />
  <name>Polar Plume - Al/Mesh, Al/Poly, C/Poly - 512x512 -3min cadence</name>
  <COT_info deleted="FALSE" lastUsed="2008-07-30T08:41:12Z" version="1577" locked="FALSE"
    tag="C5120256875C/1577" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>0</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-A</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>360</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>88</Call>
      <COT_SEQ>06B0718DB202/2787</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-18C5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="SAKO, Nobuharu" dateTime="2011-11-23T04:29:25Z" />
  <name>Eclipse20111125_Ti-Poly_Movie_DCpnt-duration-25min</name>
  <COT_info deleted="FALSE" lastUsed="2011-11-23T04:40:07Z" version="18C5" locked="FALSE"
    tag="D1C67D680130/18C5" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>1</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-A</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="2">
      <Call>2</Call>
      <COT_SUBR>Subr-B</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>64</Call>
      <COT_SEQ>566161B679B4/2B4D</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>65</Call>
      <COT_SEQ>B4CE54C127E2/2B4E</COT_SEQ>
      <Repeat>75</Repeat>
      <Interval>40</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-1844.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="BANDO, Takamasa" dateTime="2011-04-20T09:10:48Z" />
  <name>AR Standard-A(Filter-Ratio) with PFB, thin-Be context, 384x384 at 1064 1048, 80s cad</name>
  <COT_info deleted="FALSE" lastUsed="2011-04-20T09:12:23Z" version="1844" locked="FALSE"
    tag="A9831F4737E2/1844" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>0</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-A</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="2">
      <Call>2</Call>
      <COT_SUBR>Subr-B</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>19</Call>
      <COT_SEQ>C9814D3B8B68/2A9C</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="2">
      <Call>62</Call>
      <COT_SEQ>ECBE2463E6A3/2B28</COT_SEQ>
      <Repeat>4</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>2</Call>
      <COT_SEQ>ED5F03093896/2AF5</COT_SEQ>
      <Repeat>20</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
  </SUBR>
</PROG>
