=== LucasGuliano/COT/COT_Data/PRG/XRTPRG.dtd
<!ELEMENT PROG (modified*, name, COT_info*, COT_slot*, COT_reserved*, MAIN_RPT, MAIN, SUBR, SUBR, SUBR, SUBR)>

<!ELEMENT MAIN_RPT (#PCDATA)>
<!ELEMENT MAIN (MAIN_ENTRY, (MAIN_ENTRY, (MAIN_ENTRY, (MAIN_ENTRY, (MAIN_ENTRY, (MAIN_ENTRY, (MAIN_ENTRY, (MAIN_ENTRY)?)?)?)?)?)?)?)?>
<!ELEMENT MAIN_ENTRY (Call, COT_SUBR*, Repeat, Interval)>
<!ATTLIST MAIN_ENTRY
	POS (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8) #REQUIRED
>
<!ELEMENT SUBR (COT_SUBR*, SUBR_ENTRY, (SUBR_ENTRY, (SUBR_ENTRY, (SUBR_ENTRY, (SUBR_ENTRY, (SUBR_ENTRY, (SUBR_ENTRY, (SUBR_ENTRY)?)?)?)?)?)?)?)?>
<!ATTLIST SUBR
	NO (1 | 2 | 3 | 4) #REQUIRED
>
<!ELEMENT SUBR_ENTRY (Call,COT_SEQ*, Repeat, Interval)>
<!ATTLIST SUBR_ENTRY
	POS (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8) #REQUIRED
>
<!ELEMENT Call (#PCDATA)>
<!ELEMENT COT_SUBR (#PCDATA)>
<!ELEMENT COT_SEQ (#PCDATA)>
<!ELEMENT Repeat (#PCDATA)>
<!ELEMENT Interval (#PCDATA)>

<!ELEMENT modified (#PCDATA)>
<!ATTLIST modified
	author CDATA #IMPLIED
	dateTime CDATA #IMPLIED
>

<!ELEMENT name (#PCDATA)>

<!ELEMENT COT_reserved (#PCDATA)>

<!ELEMENT COT_info (#PCDATA)>
<!ATTLIST COT_info
    deleted CDATA #IMPLIED
    lastUsed CDATA #IMPLIED
    version CDATA #IMPLIED
    locked CDATA #IMPLIED
>
<!ELEMENT COT_slot (#PCDATA)>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-1B9B.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="YOSHIMURA, Keiji" dateTime="2017-06-12T20:45:35Z" />
  <name>Stray light study 2017-8 ; med-Be, 2x2 full FOV(1min-cad) and 2x2 256 on AR(10sec-cad) </name>
  <COT_info deleted="FALSE" lastUsed="2017-06-15T02:11:00Z" version="1B9B" locked="FALSE"
    tag="9F9542D7F5A6/1B9B" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>1</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-A</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="2">
      <Call>2</Call>
      <COT_SUBR>Subr-B</COT_SUBR>
      <Repeat>10</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="3">
      <Call>3</Call>
      <COT_SUBR>Subr-C</COT_SUBR>
      <Repeat>6</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>41</Call>
      <COT_SEQ>217373BD5159/2DE4</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>300</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>4</Call>
      <COT_SEQ>DE97041C6BB3/2D74</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>20</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>31</Call>
      <COT_SEQ>7AE205C483F4/2CEB</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="2">
      <Call>4</Call>
      <COT_SEQ>DE97041C6BB3/2D74</COT_SEQ>
      <Repeat>3</Repeat>
      <Interval>20</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-155B.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="NISHIDA, Keisuke" dateTime="2008-05-27T02:43:09Z" />
  <name>CCD Monitor During Bakeout - G-Band 45ms and 63ms - 1kx1k - Q90 - 1st Quadrant</name>
  <COT_info deleted="FALSE" lastUsed="2008-08-04T04:14:37Z" version="155B" locked="FALSE"
    tag="7FD521288F4D/155B" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>1</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-A</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>13</Call>
      <COT_SEQ>A62147E7A651/275C</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-1832.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="GRIGIS, Paolo" dateTime="2010-11-01T02:04:34Z" />
  <name>CME watch - Ti/poly - long / short  - 1024 FOV - 2x2 - shifted for NW limb - with G-band context</name>
  <COT_info deleted="FALSE" lastUsed="2010-11-01T02:06:51Z" version="1832" locked="FALSE"
    tag="530B79A28D24/1832" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>0</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-A</COT_SUBR>
      <Repeat>10</Repeat>
      <Interval>8</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="2">
      <Call>2</Call>
      <COT_SUBR>Subr-B</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>45</Call>
      <COT_SEQ>C8C17F30F601/2AE9</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>180</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>33</Call>
      <COT_SEQ>672769252308/2985</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>8</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-1587.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="KOTOKU, Junichi" dateTime="2008-07-08T10:01:29Z" />
  <name>CCD Monitor During Bakeout - G-Band 45ms and 63ms - 1kx1k - Q90 - 4th Quadrant-rev</name>
  <COT_info deleted="FALSE" lastUsed="2008-07-10T03:54:58Z" version="1587" locked="FALSE"
    tag="381C0419D3DD/1587" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>1</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-A</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>24</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>54</Call>
      <COT_SEQ>832F50D335DA/275B</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>24</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-1441.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="SHIMOJO, Masumi" dateTime="2008-02-28T03:34:42Z" />
  <name>CH (Al/poly) - 50s cad - 16s exp - FOV512</name>
  <COT_info deleted="FALSE" lastUsed="2007-10-31T02:41:47Z" version="1441" locked="FALSE"
    tag="4FA02EF2C056/1441" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>0</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-A</COT_SUBR>
      <Repeat>2</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="2">
      <Call>2</Call>
      <COT_SUBR>Subr-B</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>45</Call>
      <COT_SEQ>E757215835E7/25B2</COT_SEQ>
      <Repeat>30</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="2">
      <Call>55</Call>
      <COT_SEQ>AE0221D24521/25B4</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>55</Call>
      <COT_SEQ>AE0221D24521/25B4</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/Trash/XRTPRG-1302.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 1.0x14 (1571) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="BANDO, Takamasa" dateTime="2008-02-19T07:58:24Z" />
  <name>Program 2</name>
  <COT_info deleted="FALSE" lastUsed="2007-01-22T05:04:15Z" version="1302" locked="FALSE"
    tag="00003DF4297C/1302" COTversion="1.0x14" COTbuild="1571" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>1</MAIN_RPT>
  <MAIN>
  </MAIN>
  <SUBR NO="1">
  </SUBR>
  <SUBR NO="2">
  </SUBR>
  <SUBR NO="3">
  </SUBR>
  <SUBR NO="4">
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-171B.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="KANO, Ryouhei" dateTime="2009-10-10T02:33:19Z" />
  <name>Synoptic Q95 2x2 - Al/poly(362/2897) + Dark cal(2x2 4x4 8x8 512 Q98) + Ti-poly(512/4096) + G-band(16)</name>
  <COT_info deleted="FALSE" lastUsed="2009-10-20T02:32:39Z" version="171B" locked="FALSE"
    tag="B9220D9D8372/171B" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>1</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-A</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>24</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>44</Call>
      <COT_SEQ>F09116741807/2995</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>8</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="2">
      <Call>58</Call>
      <COT_SEQ>9E686155D92D/28A3</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="3">
      <Call>35</Call>
      <COT_SEQ>58D97494F087/28AA</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>8</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="4">
      <Call>11</Call>
      <COT_SEQ>3C647339F452/27C6</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-157E.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="KOTOKU, Junichi" dateTime="2008-07-08T08:34:46Z" />
  <name>Al/poly  no compression 512x256 2x2bin No1</name>
  <COT_info deleted="FALSE" lastUsed="2008-07-08T05:43:32Z" version="157E" locked="FALSE"
    tag="11834FF74F5E/157E" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>0</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-A</COT_SUBR>
      <Repeat>30</Repeat>
      <Interval>1800</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="2">
      <Call>2</Call>
      <COT_SUBR>Subr-B</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>60</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>71</Call>
      <COT_SEQ>05AF4E290965/278F</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>60</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>35</Call>
      <COT_SEQ>DF3D0E994525/2790</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>60</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
  </SUBR>
</PROG>
