=== LucasGuliano/COT/COT_Data/PRG/XRTPRG.dtd
<!ELEMENT PROG (modified*, name, COT_info*, COT_slot*, COT_reserved*, MAIN_RPT, MAIN, SUBR, SUBR, SUBR, SUBR)>

<!ELEMENT MAIN_RPT (#PCDATA)>
<!ELEMENT MAIN (MAIN_ENTRY, (MAIN_ENTRY, (MAIN_ENTRY, (MAIN_ENTRY, (MAIN_ENTRY, (MAIN_ENTRY, (MAIN_ENTRY, (MAIN_ENTRY)?)?)?)?)?)?)?)?>
<!ELEMENT MAIN_ENTRY (Call, COT_SUBR*, Repeat, Interval)>
<!ATTLIST MAIN_ENTRY
	POS (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8) #REQUIRED
>
<!ELEMENT SUBR (COT_SUBR*, SUBR_ENTRY, (SUBR_ENTRY, (SUBR_ENTRY, (SUBR_ENTRY, (SUBR_ENTRY, (SUBR_ENTRY, (SUBR_ENTRY, (SUBR_ENTRY)?)?)?)?)?)?)?)?>
<!ATTLIST SUBR
	NO (1 | 2 | 3 | 4) #REQUIRED
>
<!ELEMENT SUBR_ENTRY (Call,COT_SEQ*, Repeat, Interval)>
<!ATTLIST SUBR_ENTRY
	POS (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8) #REQUIRED
>
<!ELEMENT Call (#PCDATA)>
<!ELEMENT COT_SUBR (#PCDATA)>
<!ELEMENT COT_SEQ (#PCDATA)>
<!ELEMENT Repeat (#PCDATA)>
<!ELEMENT Interval (#PCDATA)>

<!ELEMENT modified (#PCDATA)>
<!ATTLIST modified
	author CDATA #IMPLIED
	dateTime CDATA #IMPLIED
>

<!ELEMENT name (#PCDATA)>

<!ELEMENT COT_reserved (#PCDATA)>

<!ELEMENT COT_info (#PCDATA)>
<!ATTLIST COT_info
    deleted CDATA #IMPLIED
    lastUsed CDATA #IMPLIED
    version CDATA #IMPLIED
    locked CDATA #IMPLIED
>
<!ELEMENT COT_slot (#PCDATA)>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-14F1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="CIRTAIN, Jonathan" dateTime="2008-03-04T02:33:42Z" />
  <name>CH AL/Poly + Be/thin + GBand - 512x512 - Disk Center</name>
  <COT_info deleted="FALSE" lastUsed="2008-03-04T02:42:50Z" version="14F1" locked="FALSE"
    tag="969709B53AF8/14F1" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>0</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-A</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>7200</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>38</Call>
      <COT_SEQ>1D921FF55B1C/26CB</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="2">
      <Call>64</Call>
      <COT_SEQ>D96812A0DEFE/26CC</COT_SEQ>
      <Repeat>10</Repeat>
      <Interval>16</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-17ED.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="KANO, Ryouhei" dateTime="2010-07-27T06:47:41Z" />
  <name>*** OLD *** AR Standard-A(Filter-Ratio) for FW1=Open, 384x384 at 1064 1048, 2min-cad</name>
  <COT_info deleted="FALSE" lastUsed="2010-07-30T03:52:14Z" version="17ED" locked="FALSE"
    tag="D02E31816302/17ED" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>0</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-A</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="2">
      <Call>2</Call>
      <COT_SUBR>Subr-B</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>76</Call>
      <COT_SEQ>F39556E72092/2A14</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="2">
      <Call>96</Call>
      <COT_SEQ>8B9A4A80F3B4/2A86</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>78</Call>
      <COT_SEQ>1C4D78CC6CF3/2A16</COT_SEQ>
      <Repeat>20</Repeat>
      <Interval>240</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-1C35.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="MOORE, Christopher" dateTime="2019-03-08T22:33:36Z" />
  <name>Program 6</name>
  <COT_info deleted="FALSE" lastUsed="2019-03-08T22:16:57Z" version="1C35" locked="FALSE"
    tag="D4D108BEC1B0/1C35" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>1</MAIN_RPT>
  <MAIN>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-1A87.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="REEVES, Kathy" dateTime="2015-05-20T18:23:48Z" />
  <name>EVE Rocket Cal - Synoptic 6-filter + CME Watch</name>
  <COT_info deleted="FALSE" lastUsed="2015-05-21T01:56:06Z" version="1A87" locked="FALSE"
    tag="4AF519BCC82B/1A87" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>1</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-A</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>24</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="2">
      <Call>2</Call>
      <COT_SUBR>Subr-B</COT_SUBR>
      <Repeat>2</Repeat>
      <Interval>24</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="3">
      <Call>3</Call>
      <COT_SUBR>Subr-C</COT_SUBR>
      <Repeat>86</Repeat>
      <Interval>40</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="4">
      <Call>4</Call>
      <COT_SUBR>Subr-D</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>24</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>33</Call>
      <COT_SEQ>FF2135DBC632/2D28</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>8</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="2">
      <Call>5</Call>
      <COT_SEQ>8E2E20BB6B2A/2938</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="3">
      <Call>40</Call>
      <COT_SEQ>983F2BBE58A3/2D12</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>8</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="4">
      <Call>6</Call>
      <COT_SEQ>1C0041FB3B34/2C93</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>46</Call>
      <COT_SEQ>205014AEA72F/2839</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="2">
      <Call>77</Call>
      <COT_SEQ>1DE90D807446/2D29</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="3">
      <Call>72</Call>
      <COT_SEQ>45611892D3C4/2A1C</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>29</Call>
      <COT_SEQ>5C0A2EF21D0E/2C83</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>46</Call>
      <COT_SEQ>205014AEA72F/2839</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="2">
      <Call>77</Call>
      <COT_SEQ>1DE90D807446/2D29</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="3">
      <Call>72</Call>
      <COT_SEQ>45611892D3C4/2A1C</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-1B29.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="REEVES, Kathy" dateTime="2016-04-27T15:59:01Z" />
  <name>AR Monitoring (HOP306) - Al-poly, 384x384, 60s cad, with G-band (3ms/ 3ms VLS=CLS)</name>
  <COT_info deleted="FALSE" lastUsed="2016-04-27T15:41:57Z" version="1B29" locked="FALSE"
    tag="3BFB7D272CA4/1B29" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>0</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-A</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="2">
      <Call>2</Call>
      <COT_SUBR>Subr-B</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>0</Call>
      <COT_SEQ>D19729CD92B2/2D88</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>55</Call>
      <COT_SEQ>AA7014F988C0/2DD2</COT_SEQ>
      <Repeat>60</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-1711.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="LEE, Jin-Yi" dateTime="2009-09-24T03:14:06Z" />
  <name>AR/filament - C/poly+Thin-Be - 1x1 384x384 AEC1 - 2x2 768x768 AEC2</name>
  <COT_info deleted="FALSE" lastUsed="2009-09-24T03:30:41Z" version="1711" locked="FALSE"
    tag="C95648A3D94D/1711" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>0</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-A</COT_SUBR>
      <Repeat>10</Repeat>
      <Interval>20</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="2">
      <Call>2</Call>
      <COT_SUBR>Subr-B</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>66</Call>
      <COT_SEQ>44A6493022ED/298E</COT_SEQ>
      <Repeat>3</Repeat>
      <Interval>240</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="2">
      <Call>74</Call>
      <COT_SEQ>168D76766FB9/298F</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>8</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>72</Call>
      <COT_SEQ>B49611070F00/2982</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>8</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-1828.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="ISHIBASHI, Bish" dateTime="2011-05-04T06:46:23Z" />
  <name>Flare Standard Obs. with eruptions mode-A (FW1=Open )</name>
  <COT_info deleted="FALSE" lastUsed="2013-05-31T19:19:36Z" version="1828" locked="FALSE"
    tag="88A34E207D52/1828" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>1</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-A</COT_SUBR>
      <Repeat>30</Repeat>
      <Interval>40</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="2">
      <Call>2</Call>
      <COT_SUBR>Subr-B</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="3">
      <Call>3</Call>
      <COT_SUBR>Subr-C</COT_SUBR>
      <Repeat>30</Repeat>
      <Interval>120</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="4">
      <Call>2</Call>
      <COT_SUBR>Subr-B</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="5">
      <Call>3</Call>
      <COT_SUBR>Subr-C</COT_SUBR>
      <Repeat>30</Repeat>
      <Interval>120</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="6">
      <Call>2</Call>
      <COT_SUBR>Subr-B</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="7">
      <Call>3</Call>
      <COT_SUBR>Subr-C</COT_SUBR>
      <Repeat>30</Repeat>
      <Interval>120</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="8">
      <Call>4</Call>
      <COT_SUBR>Subr-D</COT_SUBR>
      <Repeat>24</Repeat>
      <Interval>1200</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>58</Call>
      <COT_SEQ>6C380D339905/2A88</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="2">
      <Call>64</Call>
      <COT_SEQ>61CF4CDD269B/2AD8</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>59</Call>
      <COT_SEQ>8F750E7933A4/2A8B</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>58</Call>
      <COT_SEQ>6C380D339905/2A88</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="2">
      <Call>60</Call>
      <COT_SEQ>957F3D139E75/2A8C</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>61</Call>
      <COT_SEQ>13BF58ACEDF0/2A8D</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
  </SUBR>
</PROG>

=== LucasGuliano/COT/COT_Data/PRG/XRTPRG-1A1A.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PROG SYSTEM "XRTPRG.dtd">
<PROG>
  <modified author="TAKEDA, Aki" dateTime="2014-05-06T02:44:54Z" />
  <name>Stray light study ;Ti-poly with G-band VLS=close; 2x2 full FOV(1min-cad) and 1x1 384 on AR(10sec-cad)</name>
  <COT_info deleted="FALSE" lastUsed="2014-05-14T06:15:42Z" version="1A1A" locked="FALSE"
    tag="569D10DB1268/1A1A" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_reserved>0</COT_reserved>
  <MAIN_RPT>1</MAIN_RPT>
  <MAIN>
    <MAIN_ENTRY POS="1">
      <Call>1</Call>
      <COT_SUBR>Subr-A</COT_SUBR>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
    <MAIN_ENTRY POS="2">
      <Call>2</Call>
      <COT_SUBR>Subr-B</COT_SUBR>
      <Repeat>12</Repeat>
      <Interval>4</Interval>
    </MAIN_ENTRY>
  </MAIN>
  <SUBR NO="1">
  <COT_SUBR>Subr-A</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>98</Call>
      <COT_SEQ>45982037CCC9/2CCE</COT_SEQ>
      <Repeat>6</Repeat>
      <Interval>20</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="2">
  <COT_SUBR>Subr-B</COT_SUBR>
    <SUBR_ENTRY POS="1">
      <Call>21</Call>
      <COT_SEQ>4B741017B183/2CCF</COT_SEQ>
      <Repeat>1</Repeat>
      <Interval>4</Interval>
    </SUBR_ENTRY>
    <SUBR_ENTRY POS="2">
      <Call>98</Call>
      <COT_SEQ>45982037CCC9/2CCE</COT_SEQ>
      <Repeat>6</Repeat>
      <Interval>20</Interval>
    </SUBR_ENTRY>
  </SUBR>
  <SUBR NO="3">
  <COT_SUBR>Subr-C</COT_SUBR>
  </SUBR>
  <SUBR NO="4">
  <COT_SUBR>Subr-D</COT_SUBR>
  </SUBR>
</PROG>
