=== LucasGuliano/COT/COT_Data/FLT/XRTFLT.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT FLT_TBL (modified*, name*, COT_info*, COT_slot*, RD, RD, RD, RD, RD, RD, RD, RD, RD, RD, RD, RD)>

<!ELEMENT RD (#PCDATA)>
<!ATTLIST RD
	NO (A1 | A2 | A3 | A4 | A5 | A6 | B1 | B2 | B3 | B4 | B5 | B6) #IMPLIED
	name CDATA #IMPLIED
	unit CDATA #IMPLIED
>

<!ELEMENT modified (#PCDATA)>
<!ATTLIST modified
	author CDATA #IMPLIED
	dateTime CDATA #IMPLIED
>

<!ELEMENT name (#PCDATA)>
<!ELEMENT COT_info (#PCDATA)>
<!ATTLIST COT_info
    deleted CDATA #IMPLIED
    lastUsed CDATA #IMPLIED
    version CDATA #IMPLIED
>
<!ELEMENT COT_slot (#PCDATA)>

=== LucasGuliano/COT/COT_Data/FLT/XRTFLT-0001.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE FLT_TBL SYSTEM "XRTFLT.dtd">
<FLT_TBL>
  <modified author="SHIMOJO, Masumi" dateTime="2008-02-28T03:34:43Z" />
  <name>2005090151-2</name>
  <COT_info deleted="FALSE" lastUsed="2014-12-24T17:33:17Z" version="0001" locked="FALSE"
    tag="0000667D42C8/0001" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <RD name="A1" unit="(1/16)MdpExposureNumber">0</RD>
  <RD name="A2" unit="(1/16)MdpExposureNumber">8</RD>
  <RD name="A3" unit="(1/16)MdpExposureNumber">24</RD>
  <RD name="A4" unit="(1/16)MdpExposureNumber">60</RD>
  <RD name="A5" unit="(1/16)MdpExposureNumber">128</RD>
  <RD name="A6" unit="(1/16)MdpExposureNumber">179</RD>
  <RD name="B1" unit="(1/16)MdpExposureNumber">0</RD>
  <RD name="B2" unit="(1/16)MdpExposureNumber">1</RD>
  <RD name="B3" unit="(1/16)MdpExposureNumber">51</RD>
  <RD name="B4" unit="(1/16)MdpExposureNumber">0</RD>
  <RD name="B5" unit="(1/16)MdpExposureNumber">265</RD>
  <RD name="B6" unit="(1/16)MdpExposureNumber">371</RD>
</FLT_TBL>
