=== LucasGuliano/COT/COT_Data/PAR/XRTPAR.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT PARM (modified*, name, COT_info*, COT_slot*, FltA_L1, FltB_L1, FltA_L2, FltB_L2, AspectShutter, ShutterMode, ImageType, Exposure, Calibration, Resolution)>

<!ELEMENT FltA_L1 (#PCDATA)>
<!ELEMENT FltA_L2 (#PCDATA)>
<!ELEMENT FltB_L1 (#PCDATA)>
<!ELEMENT FltB_L2 (#PCDATA)>
<!ELEMENT AspectShutter (#PCDATA)>
<!ELEMENT ShutterMode (#PCDATA)>
<!ELEMENT ImageType (#PCDATA)>
<!ELEMENT Exposure (#PCDATA)>
<!ELEMENT Calibration (#PCDATA)>
<!ELEMENT Resolution (#PCDATA)>

<!ELEMENT modified (#PCDATA)>
<!ATTLIST modified
	author CDATA #IMPLIED
	dateTime CDATA #IMPLIED
>

<!ELEMENT modified (#PCDATA)>
<!ATTLIST modified
	author CDATA #IMPLIED
	dateTime CDATA #IMPLIED
>

<!ELEMENT name (#PCDATA)>

<!ELEMENT COT_info (#PCDATA)>
<!ATTLIST COT_info
    deleted CDATA #IMPLIED
    lastUsed CDATA #IMPLIED
    version CDATA #IMPLIED
>
<!ELEMENT COT_slot (#PCDATA)>

=== LucasGuliano/COT/COT_Data/PAR/XRTPAR-36B9.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PARM SYSTEM "XRTPAR.dtd">
<PARM>
  <modified author="SHIMOJO, Masumi" dateTime="2008-02-28T03:34:43Z" />
  <name>Ti/Poly - 1x1 - 4096ms</name>
  <COT_info deleted="FALSE" lastUsed="2014-07-09T05:36:45Z" version="36B9" locked="FALSE"
    tag="92F45CAECF6C/36B9" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <FltA_L1>0</FltA_L1>
  <FltB_L1>2</FltB_L1>
  <FltA_L2>0</FltA_L2>
  <FltB_L2>2</FltB_L2>
  <AspectShutter>0</AspectShutter>
  <ShutterMode>0</ShutterMode>
  <ImageType>0</ImageType>
  <Exposure>23</Exposure>
  <Calibration>0</Calibration>
  <Resolution>0</Resolution>
</PARM>

=== LucasGuliano/COT/COT_Data/PAR/XRTPAR-37D3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x39 (2080) -->
<!DOCTYPE PARM SYSTEM "XRTPAR.dtd">
<PARM>
  <modified author="LEE, Jin-Yi" dateTime="2009-05-11T00:41:12Z" />
  <name>Al/Mesh - 2x2 - 723ms</name>
  <COT_info deleted="FALSE" lastUsed="2023-11-27T10:43:59Z" version="37D3" locked="FALSE"
    tag="F9983CD5C035/37D3" COTversion="2.0x39" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>97</COT_slot>
  <FltA_L1>0</FltA_L1>
  <FltB_L1>1</FltB_L1>
  <FltA_L2>0</FltA_L2>
  <FltB_L2>1</FltB_L2>
  <AspectShutter>0</AspectShutter>
  <ShutterMode>0</ShutterMode>
  <ImageType>0</ImageType>
  <Exposure>18</Exposure>
  <Calibration>0</Calibration>
  <Resolution>1</Resolution>
</PARM>

=== LucasGuliano/COT/COT_Data/Trash/XRTPAR-38EA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x39 (2080) -->
<!DOCTYPE PARM SYSTEM "XRTPAR.dtd">
<PARM>
  <modified author="FREED, Michael" dateTime="2014-09-08T15:51:24Z" />
  <name>Thin-Be - 1x1 - 512ms-2</name>
  <COT_info deleted="FALSE" lastUsed="2014-09-08T15:49:54Z" version="38EA" locked="FALSE"
    tag="474D7F99D1A6/38EA" COTversion="2.0x39" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <FltA_L1>3</FltA_L1>
  <FltB_L1>0</FltB_L1>
  <FltA_L2>3</FltA_L2>
  <FltB_L2>0</FltB_L2>
  <AspectShutter>0</AspectShutter>
  <ShutterMode>0</ShutterMode>
  <ImageType>0</ImageType>
  <Exposure>17</Exposure>
  <Calibration>0</Calibration>
  <Resolution>0</Resolution>
</PARM>
