=== LucasGuliano/COT/COT_Data/PAR/XRTPAR.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT PARM (modified*, name, COT_info*, COT_slot*, FltA_L1, FltB_L1, FltA_L2, FltB_L2, AspectShutter, ShutterMode, ImageType, Exposure, Calibration, Resolution)>

<!ELEMENT FltA_L1 (#PCDATA)>
<!ELEMENT FltA_L2 (#PCDATA)>
<!ELEMENT FltB_L1 (#PCDATA)>
<!ELEMENT FltB_L2 (#PCDATA)>
<!ELEMENT AspectShutter (#PCDATA)>
<!ELEMENT ShutterMode (#PCDATA)>
<!ELEMENT ImageType (#PCDATA)>
<!ELEMENT Exposure (#PCDATA)>
<!ELEMENT Calibration (#PCDATA)>
<!ELEMENT Resolution (#PCDATA)>

<!ELEMENT modified (#PCDATA)>
<!ATTLIST modified
	author CDATA #IMPLIED
	dateTime CDATA #IMPLIED
>

<!ELEMENT modified (#PCDATA)>
<!ATTLIST modified
	author CDATA #IMPLIED
	dateTime CDATA #IMPLIED
>

<!ELEMENT name (#PCDATA)>

<!ELEMENT COT_info (#PCDATA)>
<!ATTLIST COT_info
    deleted CDATA #IMPLIED
    lastUsed CDATA #IMPLIED
    version CDATA #IMPLIED
>
<!ELEMENT COT_slot (#PCDATA)>

=== LucasGuliano/COT/COT_Data/PAR/XRTPAR-388C.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PARM SYSTEM "XRTPAR.dtd">
<PARM>
  <modified author="KOBELSKI, Adam" dateTime="2012-05-30T02:50:01Z" />
  <name>G-Band - 2x2 - 24ms</name>
  <COT_info deleted="FALSE" lastUsed="2012-05-31T02:11:39Z" version="388C" locked="FALSE"
    tag="D8884F34CA83/388C" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <FltA_L1>0</FltA_L1>
  <FltB_L1>3</FltB_L1>
  <FltA_L2>0</FltA_L2>
  <FltB_L2>3</FltB_L2>
  <AspectShutter>1</AspectShutter>
  <ShutterMode>0</ShutterMode>
  <ImageType>0</ImageType>
  <Exposure>8</Exposure>
  <Calibration>0</Calibration>
  <Resolution>1</Resolution>
</PARM>

=== LucasGuliano/COT/COT_Data/PAR/XRTPAR-3752.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PARM SYSTEM "XRTPAR.dtd">
<PARM>
  <modified author="REEVES, Kathy" dateTime="2008-05-07T20:16:57Z" />
  <name>C/poly - 8192 ms - 1x1</name>
  <COT_info deleted="FALSE" lastUsed="2012-03-16T20:07:08Z" version="3752" locked="FALSE"
    tag="2B9D2492047D/3752" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <FltA_L1>2</FltA_L1>
  <FltB_L1>0</FltB_L1>
  <FltA_L2>2</FltA_L2>
  <FltB_L2>0</FltB_L2>
  <AspectShutter>0</AspectShutter>
  <ShutterMode>0</ShutterMode>
  <ImageType>0</ImageType>
  <Exposure>25</Exposure>
  <Calibration>0</Calibration>
  <Resolution>0</Resolution>
</PARM>

=== LucasGuliano/COT/COT_Data/PAR/XRTPAR-3693.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PARM SYSTEM "XRTPAR.dtd">
<PARM>
  <modified author="SHIMOJO, Masumi" dateTime="2008-02-28T03:34:43Z" />
  <name>Med-Be-8x8-23142ms</name>
  <COT_info deleted="FALSE" lastUsed="2007-07-10T08:41:11Z" version="3693" locked="FALSE"
    tag="C0043091D1D7/3693" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <FltA_L1>4</FltA_L1>
  <FltB_L1>0</FltB_L1>
  <FltA_L2>0</FltA_L2>
  <FltB_L2>0</FltB_L2>
  <AspectShutter>0</AspectShutter>
  <ShutterMode>0</ShutterMode>
  <ImageType>0</ImageType>
  <Exposure>28</Exposure>
  <Calibration>0</Calibration>
  <Resolution>3</Resolution>
</PARM>

=== LucasGuliano/COT/COT_Data/PAR/XRTPAR-38BE.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PARM SYSTEM "XRTPAR.dtd">
<PARM>
  <modified author="ISHIBASHI, Bish" dateTime="2012-10-29T09:16:19Z" />
  <name>Al/poly (Thin-Be) - 4x4 - 16ms</name>
  <COT_info deleted="FALSE" lastUsed="2016-02-19T06:01:42Z" version="38BE" locked="FALSE"
    tag="879E38565EB7/38BE" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <FltA_L1>1</FltA_L1>
  <FltB_L1>0</FltB_L1>
  <FltA_L2>3</FltA_L2>
  <FltB_L2>0</FltB_L2>
  <AspectShutter>0</AspectShutter>
  <ShutterMode>0</ShutterMode>
  <ImageType>0</ImageType>
  <Exposure>7</Exposure>
  <Calibration>0</Calibration>
  <Resolution>2</Resolution>
</PARM>

=== LucasGuliano/COT/COT_Data/PAR/XRTPAR-3839.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PARM SYSTEM "XRTPAR.dtd">
<PARM>
  <modified author="YAJI, Kentaro" dateTime="2010-01-22T09:48:15Z" />
  <name>Ti/Poly - 4x4 - 16384ms</name>
  <COT_info deleted="FALSE" lastUsed="2010-02-05T09:47:21Z" version="3839" locked="FALSE"
    tag="2CA649EF2EA0/3839" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <FltA_L1>0</FltA_L1>
  <FltB_L1>2</FltB_L1>
  <FltA_L2>0</FltA_L2>
  <FltB_L2>2</FltB_L2>
  <AspectShutter>0</AspectShutter>
  <ShutterMode>0</ShutterMode>
  <ImageType>0</ImageType>
  <Exposure>27</Exposure>
  <Calibration>0</Calibration>
  <Resolution>2</Resolution>
</PARM>

=== LucasGuliano/COT/COT_Data/PAR/XRTPAR-35CA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PARM SYSTEM "XRTPAR.dtd">
<PARM>
  <modified author="SHIMOJO, Masumi" dateTime="2008-02-28T03:34:43Z" />
  <name>Med-Be (Med-Be) - 1x1 - 46284ms - Dark - Cal</name>
  <COT_info deleted="FALSE" lastUsed="2006-12-10T09:22:23Z" version="35CA" locked="FALSE"
    tag="0000005DF2D6/35CA" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <FltA_L1>4</FltA_L1>
  <FltB_L1>0</FltB_L1>
  <FltA_L2>4</FltA_L2>
  <FltB_L2>0</FltB_L2>
  <AspectShutter>0</AspectShutter>
  <ShutterMode>0</ShutterMode>
  <ImageType>1</ImageType>
  <Exposure>30</Exposure>
  <Calibration>1</Calibration>
  <Resolution>0</Resolution>
</PARM>

=== LucasGuliano/COT/COT_Data/PAR/XRTPAR-377A.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PARM SYSTEM "XRTPAR.dtd">
<PARM>
  <modified author="MINOSHIMA, Takashi" dateTime="2008-07-02T10:36:54Z" />
  <name>Thick-Be - 8x8 - 32768ms</name>
  <COT_info deleted="FALSE" lastUsed="2020-09-16T20:17:17Z" version="377A" locked="FALSE"
    tag="9E857F01D807/377A" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <FltA_L1>0</FltA_L1>
  <FltB_L1>5</FltB_L1>
  <FltA_L2>0</FltA_L2>
  <FltB_L2>5</FltB_L2>
  <AspectShutter>0</AspectShutter>
  <ShutterMode>0</ShutterMode>
  <ImageType>0</ImageType>
  <Exposure>29</Exposure>
  <Calibration>0</Calibration>
  <Resolution>3</Resolution>
</PARM>

=== LucasGuliano/COT/COT_Data/PAR/XRTPAR-364C.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PARM SYSTEM "XRTPAR.dtd">
<PARM>
  <modified author="SHIMOJO, Masumi" dateTime="2008-02-28T03:34:43Z" />
  <name>Thick-Be  - 1x1 - 46284 ms</name>
  <COT_info deleted="FALSE" lastUsed="2010-06-28T20:08:54Z" version="364C" locked="FALSE"
    tag="482003CFFBF1/364C" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <FltA_L1>0</FltA_L1>
  <FltB_L1>5</FltB_L1>
  <FltA_L2>0</FltA_L2>
  <FltB_L2>5</FltB_L2>
  <AspectShutter>0</AspectShutter>
  <ShutterMode>0</ShutterMode>
  <ImageType>0</ImageType>
  <Exposure>30</Exposure>
  <Calibration>0</Calibration>
  <Resolution>0</Resolution>
</PARM>
