=== LucasGuliano/COT/COT_Data/PAR/XRTPAR.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT PARM (modified*, name, COT_info*, COT_slot*, FltA_L1, FltB_L1, FltA_L2, FltB_L2, AspectShutter, ShutterMode, ImageType, Exposure, Calibration, Resolution)>

<!ELEMENT FltA_L1 (#PCDATA)>
<!ELEMENT FltA_L2 (#PCDATA)>
<!ELEMENT FltB_L1 (#PCDATA)>
<!ELEMENT FltB_L2 (#PCDATA)>
<!ELEMENT AspectShutter (#PCDATA)>
<!ELEMENT ShutterMode (#PCDATA)>
<!ELEMENT ImageType (#PCDATA)>
<!ELEMENT Exposure (#PCDATA)>
<!ELEMENT Calibration (#PCDATA)>
<!ELEMENT Resolution (#PCDATA)>

<!ELEMENT modified (#PCDATA)>
<!ATTLIST modified
	author CDATA #IMPLIED
	dateTime CDATA #IMPLIED
>

<!ELEMENT modified (#PCDATA)>
<!ATTLIST modified
	author CDATA #IMPLIED
	dateTime CDATA #IMPLIED
>

<!ELEMENT name (#PCDATA)>

<!ELEMENT COT_info (#PCDATA)>
<!ATTLIST COT_info
    deleted CDATA #IMPLIED
    lastUsed CDATA #IMPLIED
    version CDATA #IMPLIED
>
<!ELEMENT COT_slot (#PCDATA)>

=== LucasGuliano/COT/COT_Data/PAR/XRTPAR-37B3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PARM SYSTEM "XRTPAR.dtd">
<PARM>
  <modified author="ISHIBASHI, Bish" dateTime="2008-12-23T23:11:55Z" />
  <name>C/Poly (Med-Be) - 4x4 - 1024ms</name>
  <COT_info deleted="FALSE" lastUsed="2013-12-06T18:17:17Z" version="37B3" locked="FALSE"
    tag="B65507A4B613/37B3" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <FltA_L1>2</FltA_L1>
  <FltB_L1>0</FltB_L1>
  <FltA_L2>4</FltA_L2>
  <FltB_L2>0</FltB_L2>
  <AspectShutter>0</AspectShutter>
  <ShutterMode>0</ShutterMode>
  <ImageType>0</ImageType>
  <Exposure>19</Exposure>
  <Calibration>0</Calibration>
  <Resolution>2</Resolution>
</PARM>

=== LucasGuliano/COT/COT_Data/PAR/XRTPAR-356B.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PARM SYSTEM "XRTPAR.dtd">
<PARM>
  <modified author="SHIMOJO, Masumi" dateTime="2008-02-28T03:34:43Z" />
  <name>Al/poly - 8x8 - 1ms - Dark - Obs</name>
  <COT_info deleted="FALSE" lastUsed="2006-11-18T08:27:08Z" version="356B" locked="FALSE"
    tag="000044654B16/356B" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <FltA_L1>1</FltA_L1>
  <FltB_L1>0</FltB_L1>
  <FltA_L2>1</FltA_L2>
  <FltB_L2>0</FltB_L2>
  <AspectShutter>0</AspectShutter>
  <ShutterMode>0</ShutterMode>
  <ImageType>1</ImageType>
  <Exposure>0</Exposure>
  <Calibration>0</Calibration>
  <Resolution>3</Resolution>
</PARM>

=== LucasGuliano/COT/COT_Data/PAR/XRTPAR-352C.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PARM SYSTEM "XRTPAR.dtd">
<PARM>
  <modified author="SHIMOJO, Masumi" dateTime="2008-02-28T03:34:43Z" />
  <name>Al/poly (C/Poly) - 1x1 - 16384ms</name>
  <COT_info deleted="FALSE" lastUsed="2008-04-29T02:34:23Z" version="352C" locked="FALSE"
    tag="00003AEC398C/352C" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <FltA_L1>1</FltA_L1>
  <FltB_L1>0</FltB_L1>
  <FltA_L2>2</FltA_L2>
  <FltB_L2>0</FltB_L2>
  <AspectShutter>0</AspectShutter>
  <ShutterMode>0</ShutterMode>
  <ImageType>0</ImageType>
  <Exposure>27</Exposure>
  <Calibration>0</Calibration>
  <Resolution>0</Resolution>
</PARM>

=== LucasGuliano/COT/COT_Data/PAR/XRTPAR-38CF.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PARM SYSTEM "XRTPAR.dtd">
<PARM>
  <modified author="KOBELSKI, Adam" dateTime="2013-08-21T04:05:06Z" />
  <name>Thin-Be - 1x1 - 2897ms</name>
  <COT_info deleted="FALSE" lastUsed="2019-10-21T20:15:33Z" version="38CF" locked="FALSE"
    tag="36D50B7FFFA6/38CF" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <FltA_L1>3</FltA_L1>
  <FltB_L1>0</FltB_L1>
  <FltA_L2>3</FltA_L2>
  <FltB_L2>0</FltB_L2>
  <AspectShutter>0</AspectShutter>
  <ShutterMode>0</ShutterMode>
  <ImageType>0</ImageType>
  <Exposure>22</Exposure>
  <Calibration>0</Calibration>
  <Resolution>0</Resolution>
</PARM>

=== LucasGuliano/COT/COT_Data/PAR/XRTPAR-3678.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PARM SYSTEM "XRTPAR.dtd">
<PARM>
  <modified author="KANO, Ryouhei" dateTime="2009-01-16T05:21:16Z" />
  <name>Ti/Poly (Thick-Al) - 4x4 - 512ms</name>
  <COT_info deleted="FALSE" lastUsed="2012-03-03T03:19:54Z" version="3678" locked="FALSE"
    tag="D6AC1C38A971/3678" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <FltA_L1>0</FltA_L1>
  <FltB_L1>2</FltB_L1>
  <FltA_L2>0</FltA_L2>
  <FltB_L2>4</FltB_L2>
  <AspectShutter>0</AspectShutter>
  <ShutterMode>0</ShutterMode>
  <ImageType>0</ImageType>
  <Exposure>17</Exposure>
  <Calibration>0</Calibration>
  <Resolution>2</Resolution>
</PARM>

=== LucasGuliano/COT/COT_Data/PAR/XRTPAR-378F.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PARM SYSTEM "XRTPAR.dtd">
<PARM>
  <modified author="SAVCHEVA, Antonia" dateTime="2008-09-01T00:32:42Z" />
  <name>Al/mesh - 1x1 - 32768ms</name>
  <COT_info deleted="FALSE" lastUsed="2008-09-12T04:08:46Z" version="378F" locked="FALSE"
    tag="46C21E4DC19B/378F" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <FltA_L1>0</FltA_L1>
  <FltB_L1>1</FltB_L1>
  <FltA_L2>0</FltA_L2>
  <FltB_L2>1</FltB_L2>
  <AspectShutter>0</AspectShutter>
  <ShutterMode>0</ShutterMode>
  <ImageType>0</ImageType>
  <Exposure>29</Exposure>
  <Calibration>0</Calibration>
  <Resolution>0</Resolution>
</PARM>

=== LucasGuliano/COT/COT_Data/PAR/XRTPAR-3827.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x39 (2080) -->
<!DOCTYPE PARM SYSTEM "XRTPAR.dtd">
<PARM>
  <modified author="MASUDA, Satoshi" dateTime="2009-12-16T02:57:40Z" />
  <name>Med-Al (Med-Al + Thick-Al) - 2x2 - 2048ms</name>
  <COT_info deleted="FALSE" lastUsed="2022-11-09T02:21:46Z" version="3827" locked="FALSE"
    tag="ADFC118DADDB/3827" COTversion="2.0x39" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <FltA_L1>5</FltA_L1>
  <FltB_L1>0</FltB_L1>
  <FltA_L2>5</FltA_L2>
  <FltB_L2>4</FltB_L2>
  <AspectShutter>0</AspectShutter>
  <ShutterMode>0</ShutterMode>
  <ImageType>0</ImageType>
  <Exposure>21</Exposure>
  <Calibration>0</Calibration>
  <Resolution>1</Resolution>
</PARM>

=== LucasGuliano/COT/COT_Data/PAR/XRTPAR-388F.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE PARM SYSTEM "XRTPAR.dtd">
<PARM>
  <modified author="SAKAO, Taro" dateTime="2012-06-04T08:20:08Z" />
  <name>Ti/Poly - 1x1 - 4096ms - Dark</name>
  <COT_info deleted="FALSE" lastUsed="2012-06-04T08:40:20Z" version="388F" locked="FALSE"
    tag="77E66350761C/388F" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <FltA_L1>0</FltA_L1>
  <FltB_L1>2</FltB_L1>
  <FltA_L2>0</FltA_L2>
  <FltB_L2>2</FltB_L2>
  <AspectShutter>0</AspectShutter>
  <ShutterMode>0</ShutterMode>
  <ImageType>1</ImageType>
  <Exposure>23</Exposure>
  <Calibration>0</Calibration>
  <Resolution>0</Resolution>
</PARM>
