=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ.dtd
<!ELEMENT SEQN (modified*, name, COT_info*, COT_slot*, COT_AEC*, COT_ROI*, COT_CMP* ,(SEQN_ENTRY, (SEQN_ENTRY, (SEQN_ENTRY, (SEQN_ENTRY, (SEQN_ENTRY, (SEQN_ENTRY, (SEQN_ENTRY, (SEQN_ENTRY)?)?)?)?)?)?)?)?)>

<!ELEMENT COT_AEC (#PCDATA)>

<!ELEMENT COT_ROI (#PCDATA)>

<!ELEMENT COT_CMP (#PCDATA)>

<!ELEMENT SEQN_ENTRY (PARM_NO, COT_PARM*, REGN_NO, COMP_CODE, AEC_NO,
BUF_NO, DMF, SEQN_INT)>
<!ATTLIST SEQN_ENTRY
	POS (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8) #IMPLIED
>

<!ELEMENT PARM_NO (#PCDATA)>
<!ELEMENT COT_PARM (#PCDATA)>
<!ELEMENT REGN_NO (#PCDATA)>
<!ELEMENT COMP_CODE (#PCDATA)>
<!ELEMENT AEC_NO (#PCDATA)>
<!ELEMENT BUF_NO (#PCDATA)>
<!ELEMENT DMF (#PCDATA)>
<!ELEMENT SEQN_INT (#PCDATA)>

<!ELEMENT modified (#PCDATA)>
<!ATTLIST modified
	author CDATA #IMPLIED
	dateTime CDATA #IMPLIED
>

<!ELEMENT name (#PCDATA)>

<!ELEMENT COT_info (#PCDATA)>
<!ATTLIST COT_info
    deleted CDATA #IMPLIED
    lastUsed CDATA #IMPLIED
    version CDATA #IMPLIED
>
<!ELEMENT COT_slot (#PCDATA)>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-2BD4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="MCKENZIE, David" dateTime="2012-07-04T04:49:43Z" />
  <name>Ti/Poly (Thick Al) - 512FOV - 24s cad - AEC3 - 1064 1048 - With 384PFB</name>
  <COT_info deleted="FALSE" lastUsed="2012-07-04T04:27:43Z" version="2BD4" locked="FALSE"
    tag="E61837C93765/2BD4" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>2</PARM_NO>
    <COT_PARM>000009C67372/353A</COT_PARM>
    <REGN_NO>10</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1064" vcenter="1048" width="512" height="512" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>3</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>12</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="2">
    <PARM_NO>2</PARM_NO>
    <COT_PARM>000009C67372/353A</COT_PARM>
    <REGN_NO>5</REGN_NO>
    <COT_fov FOV_type="preflare" hcenter="1064" vcenter="1048" width="384" height="384" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>3</AEC_NO>
    <BUF_NO>1</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>12</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="3">
    <PARM_NO>2</PARM_NO>
    <COT_PARM>000009C67372/353A</COT_PARM>
    <REGN_NO>5</REGN_NO>
    <COT_fov FOV_type="preflare" hcenter="1064" vcenter="1048" width="384" height="384" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>3</AEC_NO>
    <BUF_NO>2</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>12</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="4">
    <PARM_NO>2</PARM_NO>
    <COT_PARM>000009C67372/353A</COT_PARM>
    <REGN_NO>5</REGN_NO>
    <COT_fov FOV_type="preflare" hcenter="1064" vcenter="1048" width="384" height="384" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>3</AEC_NO>
    <BUF_NO>3</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>12</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-2B29.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="TESTA, Paola" dateTime="2011-03-10T02:47:49Z" />
  <name>G-band and Dark (2sec) - 512x512 - 1064 1048 - Q98</name>
  <COT_info deleted="FALSE" lastUsed="2011-03-10T02:45:49Z" version="2B29" locked="FALSE"
    tag="1EAF29CC3569/2B29" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>67</PARM_NO>
    <COT_PARM>B00462C8EC2B/37C0</COT_PARM>
    <REGN_NO>7</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1064" vcenter="1048" width="512" height="512" />
    <COMP_CODE>0x728</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="2">
    <PARM_NO>3</PARM_NO>
    <COT_PARM>00007CE10EC0/3605</COT_PARM>
    <REGN_NO>7</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1064" vcenter="1048" width="512" height="512" />
    <COMP_CODE>0x728</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-2E43.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x39 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="TAKEDA, Aki" dateTime="2017-07-21T20:32:15Z" />
  <name>Al/mesh 2897 ms and G-band 1 ms - 384x384 - 1x1 - AEC0 - Q95 - at Center</name>
  <COT_info deleted="FALSE" lastUsed="2023-05-06T02:05:39Z" version="2E43" locked="FALSE"
    tag="206220E1D324/2E43" COTversion="2.0x39" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>49</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>59</PARM_NO>
    <COT_PARM>1BCC740212E1/3769</COT_PARM>
    <REGN_NO>11</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="384" height="384" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="2">
    <PARM_NO>39</PARM_NO>
    <COT_PARM>A2AD16059148/3940</COT_PARM>
    <REGN_NO>13</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1200" width="384" height="384" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-2C2B.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="YOSHIMURA, Keiji" dateTime="2012-11-21T06:04:50Z" />
  <name>Thin-Be 2048 FOV, Q98, 2x2, Short and Long (256/5795)</name>
  <COT_info deleted="FALSE" lastUsed="2012-11-21T09:16:04Z" version="2C2B" locked="FALSE"
    tag="CBD10FC875FA/2C2B" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>47</PARM_NO>
    <COT_PARM>8B7B6DE3E75E/371F</COT_PARM>
    <REGN_NO>8</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="2048" height="2048" />
    <COMP_CODE>0x728</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="2">
    <PARM_NO>94</PARM_NO>
    <COT_PARM>B0F544CE8126/3720</COT_PARM>
    <REGN_NO>8</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="2048" height="2048" />
    <COMP_CODE>0x728</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-29EE.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="BANDO, Takamasa" dateTime="2010-01-11T07:17:52Z" />
  <name>Synoptic Q98 2x2 4x4 8x8 1x1 Dark cal - Ti/poly 512ms</name>
  <COT_info deleted="FALSE" lastUsed="2012-05-15T01:56:55Z" version="29EE" locked="FALSE"
    tag="A6F96C19DB16/29EE" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>23</PARM_NO>
    <COT_PARM>1AA46D2A3A80/37BE</COT_PARM>
    <REGN_NO>10</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="2048" height="2048" />
    <COMP_CODE>0x728</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="2">
    <PARM_NO>24</PARM_NO>
    <COT_PARM>A5774694FE64/37C6</COT_PARM>
    <REGN_NO>10</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="2048" height="2048" />
    <COMP_CODE>0x728</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="3">
    <PARM_NO>25</PARM_NO>
    <COT_PARM>263D38411AED/37C7</COT_PARM>
    <REGN_NO>10</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="2048" height="2048" />
    <COMP_CODE>0x728</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-2DC0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="NISHIDA, Keisuke" dateTime="2016-02-22T03:42:52Z" />
  <name>Synoptic Q98 2x2 Med-Al short(4096ms)/long(32768ms) set</name>
  <COT_info deleted="FALSE" lastUsed="2017-01-16T15:01:14Z" version="2DC0" locked="FALSE"
    tag="FCFD3D59C200/2DC0" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>99</PARM_NO>
    <COT_PARM>00006A1C853E/3585</COT_PARM>
    <REGN_NO>7</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="2048" height="2048" />
    <COMP_CODE>0x728</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="2">
    <PARM_NO>38</PARM_NO>
    <COT_PARM>9FFF0E06E382/38A7</COT_PARM>
    <REGN_NO>7</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="2048" height="2048" />
    <COMP_CODE>0x728</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-2B28.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="TESTA, Paola" dateTime="2011-03-10T02:43:20Z" />
  <name>Ti/poly (Thick-Al), thin-Be (med-Be) shorter exp, Al/Poly (Med-Be) - 512FOV - AEC3 - 1064 1048 for normal AR</name>
  <COT_info deleted="FALSE" lastUsed="2011-04-20T09:12:23Z" version="2B28" locked="FALSE"
    tag="ECBE2463E6A3/2B28" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>2</PARM_NO>
    <COT_PARM>000012DA2A1B/352F</COT_PARM>
    <REGN_NO>7</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1064" vcenter="1048" width="512" height="512" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>3</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="2">
    <PARM_NO>64</PARM_NO>
    <COT_PARM>42743B6367A2/3872</COT_PARM>
    <REGN_NO>7</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1064" vcenter="1048" width="512" height="512" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>3</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="3">
    <PARM_NO>45</PARM_NO>
    <COT_PARM>00003029D24A/358B</COT_PARM>
    <REGN_NO>7</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1064" vcenter="1048" width="512" height="512" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>3</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-2C75.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="KOBELSKI, Adam" dateTime="2013-08-19T01:13:58Z" />
  <name>Synoptic Q95 2x2 Thin-Be short(128ms)/med(723ms)/long(3897ms)</name>
  <COT_info deleted="FALSE" lastUsed="2013-11-02T03:15:46Z" version="2C75" locked="FALSE"
    tag="EDAC556C7383/2C75" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>16</PARM_NO>
    <COT_PARM>C46863026722/3883</COT_PARM>
    <REGN_NO>8</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="2048" height="2048" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="2">
    <PARM_NO>47</PARM_NO>
    <COT_PARM>7BBF31D50850/38CA</COT_PARM>
    <REGN_NO>8</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="2048" height="2048" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="3">
    <PARM_NO>59</PARM_NO>
    <COT_PARM>F08E630A2A13/38CB</COT_PARM>
    <REGN_NO>8</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="2048" height="2048" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>
