=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ.dtd
<!ELEMENT SEQN (modified*, name, COT_info*, COT_slot*, COT_AEC*, COT_ROI*, COT_CMP* ,(SEQN_ENTRY, (SEQN_ENTRY, (SEQN_ENTRY, (SEQN_ENTRY, (SEQN_ENTRY, (SEQN_ENTRY, (SEQN_ENTRY, (SEQN_ENTRY)?)?)?)?)?)?)?)?)>

<!ELEMENT COT_AEC (#PCDATA)>

<!ELEMENT COT_ROI (#PCDATA)>

<!ELEMENT COT_CMP (#PCDATA)>

<!ELEMENT SEQN_ENTRY (PARM_NO, COT_PARM*, REGN_NO, COMP_CODE, AEC_NO,
BUF_NO, DMF, SEQN_INT)>
<!ATTLIST SEQN_ENTRY
	POS (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8) #IMPLIED
>

<!ELEMENT PARM_NO (#PCDATA)>
<!ELEMENT COT_PARM (#PCDATA)>
<!ELEMENT REGN_NO (#PCDATA)>
<!ELEMENT COMP_CODE (#PCDATA)>
<!ELEMENT AEC_NO (#PCDATA)>
<!ELEMENT BUF_NO (#PCDATA)>
<!ELEMENT DMF (#PCDATA)>
<!ELEMENT SEQN_INT (#PCDATA)>

<!ELEMENT modified (#PCDATA)>
<!ATTLIST modified
	author CDATA #IMPLIED
	dateTime CDATA #IMPLIED
>

<!ELEMENT name (#PCDATA)>

<!ELEMENT COT_info (#PCDATA)>
<!ATTLIST COT_info
    deleted CDATA #IMPLIED
    lastUsed CDATA #IMPLIED
    version CDATA #IMPLIED
>
<!ELEMENT COT_slot (#PCDATA)>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-2EB9.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="REEVES, Kathy" dateTime="2021-07-23T19:50:18Z" />
  <name>Flare - multifilter (Be/thin, Be/med) - 384x384 - AEC1 - 8/256 - Be/med, Al/thick</name>
  <COT_info deleted="FALSE" lastUsed="2022-05-12T02:04:39Z" version="2EB9" locked="FALSE"
    tag="251356D48A91/2EB9" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>34</PARM_NO>
    <COT_PARM>F83561ED061E/367E</COT_PARM>
    <REGN_NO>15</REGN_NO>
    <COT_fov FOV_type="flare1" hcenter="1024" vcenter="1024" width="384" height="384" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>1</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="2">
    <PARM_NO>5</PARM_NO>
    <COT_PARM>D574788F0BF5/3664</COT_PARM>
    <REGN_NO>15</REGN_NO>
    <COT_fov FOV_type="flare1" hcenter="1024" vcenter="1024" width="384" height="384" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>1</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-2A52.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="SAVCHEVA, Antonia" dateTime="2010-06-04T19:39:20Z" />
  <name>Al/Mesh(Ti/Poly)-256FOV-10s cadence-AEC3-3</name>
  <COT_info deleted="FALSE" lastUsed="2010-06-04T19:37:35Z" version="2A52" locked="FALSE"
    tag="3F3F78A2B3BF/2A52" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>1</PARM_NO>
    <COT_PARM>0000085844B6/360E</COT_PARM>
    <REGN_NO>12</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="256" height="256" />
    <COMP_CODE>0x328</COMP_CODE>
    <AEC_NO>3</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>20</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-2C76.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="KOBELSKI, Adam" dateTime="2013-08-16T05:39:41Z" />
  <name>HOP128-Al/Mesh-1x1-512x512-AEC3-Thin_be (PFB) - Q95-at_1064</name>
  <COT_info deleted="FALSE" lastUsed="2013-08-17T01:57:48Z" version="2C76" locked="FALSE"
    tag="7A6D776CFDC2/2C76" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>80</PARM_NO>
    <COT_PARM>B80B7C5245BC/3743</COT_PARM>
    <REGN_NO>7</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1064" vcenter="1048" width="512" height="512" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>3</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="2">
    <PARM_NO>4</PARM_NO>
    <COT_PARM>000074C1DE18/353C</COT_PARM>
    <REGN_NO>5</REGN_NO>
    <COT_fov FOV_type="preflare" hcenter="1064" vcenter="1048" width="384" height="384" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>3</AEC_NO>
    <BUF_NO>1</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="3">
    <PARM_NO>4</PARM_NO>
    <COT_PARM>000074C1DE18/353C</COT_PARM>
    <REGN_NO>5</REGN_NO>
    <COT_fov FOV_type="preflare" hcenter="1064" vcenter="1048" width="384" height="384" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>3</AEC_NO>
    <BUF_NO>2</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="4">
    <PARM_NO>4</PARM_NO>
    <COT_PARM>000074C1DE18/353C</COT_PARM>
    <REGN_NO>5</REGN_NO>
    <COT_fov FOV_type="preflare" hcenter="1064" vcenter="1048" width="384" height="384" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>3</AEC_NO>
    <BUF_NO>3</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-2BD3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="YOSHIMURA, Keiji" dateTime="2012-11-19T06:58:05Z" />
  <name>G-Band Test - 33ms - VLS closed - 1x1 - 2048FOV- DPCM</name>
  <COT_info deleted="FALSE" lastUsed="2015-06-02T03:15:28Z" version="2BD3" locked="FALSE"
    tag="C04F10E44521/2BD3" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>37</PARM_NO>
    <COT_PARM>1B2A2D5A6297/3895</COT_PARM>
    <REGN_NO>6</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="2048" height="2048" />
    <COMP_CODE>0x328</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-25E5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="SHIMOJO, Masumi" dateTime="2008-02-28T03:34:42Z" />
  <name>XBP Al/poly (AEC1) - FOV384x512</name>
  <COT_info deleted="FALSE" lastUsed="2007-11-24T02:32:54Z" version="25E5" locked="FALSE"
    tag="0F8A4B779A34/25E5" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>18</PARM_NO>
    <COT_PARM>00004B0B31D2/3640</COT_PARM>
    <REGN_NO>10</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="384" height="512" />
    <COMP_CODE>0x328</COMP_CODE>
    <AEC_NO>1</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-2CB9.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="SCHANCHE, Nicole" dateTime="2014-07-23T15:34:03Z" />
  <name>Thin-Be (Med-Be) - 384FOV - AEC3 - 1064 1048 - no PFB - 10s-cad</name>
  <COT_info deleted="FALSE" lastUsed="2016-09-24T03:00:58Z" version="2CB9" locked="FALSE"
    tag="59A021758E1C/2CB9" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>58</PARM_NO>
    <COT_PARM>853E4A17E6F8/3676</COT_PARM>
    <REGN_NO>6</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1064" vcenter="1048" width="384" height="384" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>3</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>20</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-2487.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="SHIMOJO, Masumi" dateTime="2008-02-28T03:34:42Z" />
  <name>G-Band Alignment - 1x1 - 512FOV - shifted</name>
  <COT_info deleted="FALSE" lastUsed="2007-05-05T08:43:17Z" version="2487" locked="FALSE"
    tag="51BC07410928/2487" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>14</PARM_NO>
    <COT_PARM>00007CE10EC0/3605</COT_PARM>
    <REGN_NO>7</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="928" vcenter="976" width="512" height="512" />
    <COMP_CODE>0x728</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-2B8B.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="FARID, Samaiyah" dateTime="2011-10-25T02:13:36Z" />
  <name>Flare Obs. - Fale Safe Mode-no-thick-be</name>
  <COT_info deleted="FALSE" lastUsed="2011-10-26T20:19:00Z" version="2B8B" locked="FALSE"
    tag="0B6D0382F5F9/2B8B" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>77</PARM_NO>
    <COT_PARM>7E7C2C1961E1/3858</COT_PARM>
    <REGN_NO>15</REGN_NO>
    <COT_fov FOV_type="flare1" hcenter="1024" vcenter="1024" width="384" height="384" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>1</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="2">
    <PARM_NO>62</PARM_NO>
    <COT_PARM>109C5008EBD7/3675</COT_PARM>
    <REGN_NO>15</REGN_NO>
    <COT_fov FOV_type="flare1" hcenter="1024" vcenter="1024" width="384" height="384" />
    <COMP_CODE>0x72c</COMP_CODE>
    <AEC_NO>1</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="3">
    <PARM_NO>3</PARM_NO>
    <COT_PARM>00007CE10EC0/3605</COT_PARM>
    <REGN_NO>15</REGN_NO>
    <COT_fov FOV_type="flare1" hcenter="1024" vcenter="1024" width="384" height="384" />
    <COMP_CODE>0x728</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="4">
    <PARM_NO>84</PARM_NO>
    <COT_PARM>17AD4139923F/36C1</COT_PARM>
    <REGN_NO>15</REGN_NO>
    <COT_fov FOV_type="flare1" hcenter="1024" vcenter="1024" width="384" height="384" />
    <COMP_CODE>0x728</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>
