=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ.dtd
<!ELEMENT SEQN (modified*, name, COT_info*, COT_slot*, COT_AEC*, COT_ROI*, COT_CMP* ,(SEQN_ENTRY, (SEQN_ENTRY, (SEQN_ENTRY, (SEQN_ENTRY, (SEQN_ENTRY, (SEQN_ENTRY, (SEQN_ENTRY, (SEQN_ENTRY)?)?)?)?)?)?)?)?)>

<!ELEMENT COT_AEC (#PCDATA)>

<!ELEMENT COT_ROI (#PCDATA)>

<!ELEMENT COT_CMP (#PCDATA)>

<!ELEMENT SEQN_ENTRY (PARM_NO, COT_PARM*, REGN_NO, COMP_CODE, AEC_NO,
BUF_NO, DMF, SEQN_INT)>
<!ATTLIST SEQN_ENTRY
	POS (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8) #IMPLIED
>

<!ELEMENT PARM_NO (#PCDATA)>
<!ELEMENT COT_PARM (#PCDATA)>
<!ELEMENT REGN_NO (#PCDATA)>
<!ELEMENT COMP_CODE (#PCDATA)>
<!ELEMENT AEC_NO (#PCDATA)>
<!ELEMENT BUF_NO (#PCDATA)>
<!ELEMENT DMF (#PCDATA)>
<!ELEMENT SEQN_INT (#PCDATA)>

<!ELEMENT modified (#PCDATA)>
<!ATTLIST modified
	author CDATA #IMPLIED
	dateTime CDATA #IMPLIED
>

<!ELEMENT name (#PCDATA)>

<!ELEMENT COT_info (#PCDATA)>
<!ATTLIST COT_info
    deleted CDATA #IMPLIED
    lastUsed CDATA #IMPLIED
    version CDATA #IMPLIED
>
<!ELEMENT COT_slot (#PCDATA)>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-2780.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="TESTA, Paola" dateTime="2008-06-24T01:08:36Z" />
  <name>Al/poly - DPCM 2x2 - 768x768 4s no_AEC-FOV offset</name>
  <COT_info deleted="FALSE" lastUsed="2011-01-08T01:20:47Z" version="2780" locked="FALSE"
    tag="E4DE47CC41CA/2780" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>33</PARM_NO>
    <COT_PARM>00005D5E8B29/3633</COT_PARM>
    <REGN_NO>11</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1152" vcenter="904" width="768" height="768" />
    <COMP_CODE>0x328</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-2E01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="PRCHLIK, Jakub" dateTime="2017-03-16T02:28:30Z" />
  <name>Polar Monitoring - Al/mesh (6s) and Al/poly (8s) - 384FOV - Q90</name>
  <COT_info deleted="FALSE" lastUsed="2020-06-01T17:58:20Z" version="2E01" locked="FALSE"
    tag="D73847D22120/2E01" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>92</PARM_NO>
    <COT_PARM>37F043942D0E/36B5</COT_PARM>
    <REGN_NO>11</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1064" vcenter="1048" width="384" height="384" />
    <COMP_CODE>0x729</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-2923.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="MINOSHIMA, Takashi" dateTime="2009-06-22T06:45:00Z" />
  <name>Al/mesh (12s), Al/poly (16s), Ti/poly (32s) - 384x384</name>
  <COT_info deleted="FALSE" lastUsed="2009-06-19T09:38:07Z" version="2923" locked="FALSE"
    tag="74A42A3EF54C/2923" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>58</PARM_NO>
    <COT_PARM>F2C953CF080D/36C6</COT_PARM>
    <REGN_NO>9</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1064" vcenter="1048" width="384" height="384" />
    <COMP_CODE>0x729</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="2">
    <PARM_NO>27</PARM_NO>
    <COT_PARM>00001AB99241/351E</COT_PARM>
    <REGN_NO>9</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1064" vcenter="1048" width="384" height="384" />
    <COMP_CODE>0x729</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="3">
    <PARM_NO>1</PARM_NO>
    <COT_PARM>00005FEF2422/351A</COT_PARM>
    <REGN_NO>10</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1064" vcenter="1048" width="384" height="384" />
    <COMP_CODE>0x729</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-2C96.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="ISHIBASHI, Bish" dateTime="2013-11-01T07:18:47Z" />
  <name>Full Sun - Al/Poly - 4x4 - AEC2 - Active Sun</name>
  <COT_info deleted="FALSE" lastUsed="2014-05-01T04:01:28Z" version="2C96" locked="FALSE"
    tag="C97B6E953890/2C96" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>43</PARM_NO>
    <COT_PARM>021D36189771/38C0</COT_PARM>
    <REGN_NO>7</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="2048" height="2048" />
    <COMP_CODE>0x728</COMP_CODE>
    <AEC_NO>2</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-26EC.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="MASUDA, Satoshi" dateTime="2008-03-21T11:05:43Z" />
  <name>CH (Al/poly) - 16s exp- FOV512-DARK Q90</name>
  <COT_info deleted="FALSE" lastUsed="2008-03-22T06:07:51Z" version="26EC" locked="FALSE"
    tag="9AE320AD45DA/26EC" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>81</PARM_NO>
    <COT_PARM>00001ADFD271/35E2</COT_PARM>
    <REGN_NO>6</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="512" height="512" />
    <COMP_CODE>0x729</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-2740.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="SAVCHEVA, Antonia" dateTime="2008-05-09T19:51:13Z" />
  <name>Al/mesh - 512, lossless 1x1, 2x2,4x4-AR</name>
  <COT_info deleted="FALSE" lastUsed="2008-05-08T16:24:53Z" version="2740" locked="FALSE"
    tag="323A1641F958/2740" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>1</PARM_NO>
    <COT_PARM>D800038C3828/375B</COT_PARM>
    <REGN_NO>1</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="512" height="512" />
    <COMP_CODE>0x328</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="2">
    <PARM_NO>1</PARM_NO>
    <COT_PARM>3FA2667A0E6B/375C</COT_PARM>
    <REGN_NO>1</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="512" height="512" />
    <COMP_CODE>0x328</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="3">
    <PARM_NO>1</PARM_NO>
    <COT_PARM>80072B968FBA/375D</COT_PARM>
    <REGN_NO>1</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="512" height="512" />
    <COMP_CODE>0x328</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-280B.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="SAVAGE, Sabrina" dateTime="2008-10-10T05:22:58Z" />
  <name>Al/poly 8192ms Dark - FOV384</name>
  <COT_info deleted="FALSE" lastUsed="2008-10-16T00:12:34Z" version="280B" locked="FALSE"
    tag="69006AAFE65D/280B" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>8</PARM_NO>
    <COT_PARM>00004A7186D2/3500</COT_PARM>
    <REGN_NO>13</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="384" height="384" />
    <COMP_CODE>0x328</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>

=== LucasGuliano/COT/COT_Data/SEQ/XRTSEQ-2BC4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XRT Chief Observer Tool version 2.0x40 (2080) -->
<!DOCTYPE SEQN SYSTEM "XRTSEQ.dtd">
<SEQN>
  <modified author="KOBELSKI, Adam" dateTime="2012-05-25T07:11:27Z" />
  <name>Ti/poly al/mesh for ToV</name>
  <COT_info deleted="FALSE" lastUsed="2012-05-26T02:09:10Z" version="2BC4" locked="FALSE"
    tag="F17C5DCC51B3/2BC4" COTversion="2.0x40" COTbuild="2080" Mutable="TRUE" />
  <COT_slot>-1</COT_slot>
  <COT_AEC>NOT USED</COT_AEC>
  <COT_ROI>NOT USED</COT_ROI>
  <COT_CMP>NOT USED</COT_CMP>
  <SEQN_ENTRY POS="1">
    <PARM_NO>64</PARM_NO>
    <COT_PARM>0000042A469B/3542</COT_PARM>
    <REGN_NO>7</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="512" height="512" />
    <COMP_CODE>0x728</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
  <SEQN_ENTRY POS="2">
    <PARM_NO>65</PARM_NO>
    <COT_PARM>03DF05D50B88/3886</COT_PARM>
    <REGN_NO>7</REGN_NO>
    <COT_fov FOV_type="normal" hcenter="1024" vcenter="1024" width="512" height="512" />
    <COMP_CODE>0x728</COMP_CODE>
    <AEC_NO>0</AEC_NO>
    <BUF_NO>0</BUF_NO>
    <DMF>0</DMF>
    <SEQN_INT>4</SEQN_INT>
  </SEQN_ENTRY>
</SEQN>
